### ISSUE TITLE
About boost:date_time and boost::thread

### ISSUE THREAD

**Issue by mdianjun** [ClickHouse/boost#15]
I have seen the boost::date_time and boost::thread in the add_boost_thread branch.
When will they be merged into the master? @nikitamikhaylov

**Comment by mdianjun** [comment]
I push a PR which added the boost date_time src files: https://github.com/ClickHouse-Extras/boost/pull/16 .

**Comment by alexey-milovidov** [comment]
I've missed this PR.
Why do we need these libraries? Is it still relevant?
